applications:
  
  training-manager:
    app_name: training-manager
    app_image: "{{image}}"
    task_definition_name: training-manager
    memory_hard_limit: 128
    container_port: 8090
    host_port: 8090
    host_name: TRINITI
    host: http://172.16.1.157
    volume_name: manager
    source_path: /var/log/supervisor
    container_path: /var/log/supervisor
    

  AI-triniti-master-svc:  
    app_name: ai-triniti-master
    app_image: "{{image}}"
    task_definition_name: AI-triniti-master
    memory_hard_limit: 16384
    container_port: 8080
    host_port: 8080
    host_name: ai-triniti
    host: ai-triniti-master
    volume_name: supervisor
    source_path: /var/log/supervisor
    container_path: /var/log/supervisor  

  sniper-master:
    app_name: spotter-master
    app_image: "{{image}}"
    task_definition_name: spotter-master
    memory_hard_limit: 14336
    container_port: 8888
    host_port: 9000
    host_name: SPOTTER_MASTER
    host: preprodrediscluster.lydffc.0001.euw1.cache.amazonaws.com
    volume_name1: spiner
    source_path1: /sniper
    container_path1: /opt/tornado/data/faq_index
    volume_name2: superviser
    source_path2: /var/log/superviser
    container_path2: /superviser
   