applications:
  
  sniper-master:
    app_name: spiner-master
    app_image: nginx:latest
    container_port: 80
    host_port: 0
    task_cpu: 128
    task_memory: 1024
    host_name: webserver
    host: http://18.220.64.40:80
    volume_name1: nginx-volume
    source_path1: /var/log/nginx-volume
    container_path1: /nginx-volume
     volume_name2: superviser
    source_path2: /var/log/superviser
    container_path2: /superviser
   
   

  triniti-mstr:
    app_name: spiner-mstr
    app_image: nginx:latest
    container_port: 80
    host_port: 0
    task_cpu: 128
    task_memory: 1024
    host_name: webserver
    host: http://18.220.64.40:80
    volume_name1: nginx-volume
    source_path1: /var/log/nginx-volume
    container_path1: /nginx-volume
     volume_name2: superviser
    source_path2: /var/log/superviser
    container_path2: /superviser
  
  manager:
    name: "manager-prod-0-5"
    image: "940330296631.dkr.ecr.ap-southeast-1.amazonaws.com/instarem"
    tag: onprem.5
    health_check_url: "/"
    context_path_pattern: "/v/1"
    memory_hard_limit: 128
    container_port: 8090
    volume_name1: nginx-volume
    source_path1: /var/log/nginx-volume
    container_path1: /nginx-volume
     volume_name2: superviser
    source_path2: /var/log/superviser
    container_path2: /superviser