#Container-Image


app_name: chatbot-Ai
app_image: 769585693008.dkr.ecr.us-east-2.amazonaws.com/backend:latest
container_port: 80

task_cpu: 128
task_memory: 1024

host_name: webserver
host: http://18.220.64.40:80



volume_name: nginx-volume
source_path: /var/log/nginx-volume
container_path: /nginx-volume









