#Container-Image
app_name: chatbot-Ai
app_image: 769585693008.dkr.ecr.us-east-2.amazonaws.com/backend:latest
container_port: 80
task_cpu: 128
task_memory: 1024
volume_name: myvolume
source_path: /var/log/backend
container_path: /backend
