applications:
  defaults:
    app_name: 
    app_image: 
    memory_hard_limit: 
    task_definition_name: 
    container_port: 
    host_port: 
    host_name: null
    host: null
    volume_name: 
    source_path: 
    container_path: 

  morfeusadmin:
    app_name: morfeusadmin
    app_image: "{{image}}"
    memory_hard_limit: 2048
    task_definition_name: morfeus-admin
    container_port: 8080
    host_port: 8080
    #host_name: ENV_PARAM
    #host: uat
    volume_name: superviser
    source_path: /var/log/superviser
    container_path: /var/log/supervisor


  morfeus-app:
    app_name: morfeus-app-3-3-1
    app_image: "{{image}}"
    task_definition_name: morfeus
    memory_hard_limit: 4096
    container_port: 8080
    host_port: 8081
    host_name: ENV_PARAM
    host: uat
    volume_name: superviser-1
    source_path: /var/log/supervisor
    container_path: /var/log/supervisor








