applications:
  defaults:
    name:
    image:
    tag:
    container_port: 
    tg_unhealthy_threshold_count: 2
    tg_healthy_threshold_count: 5
    tg_health_check_timeout: 5
    tg_health_check_interval: 30
    memory_soft_limit:
    memory_hard_limit:
    container_path:
    volume_name: 
    source_path:
    ecs_service_name: 
    alb_priority: 
    cpu_limit:
    host_name:
    host:
  morfeusadmin:
    app_name: morfeusadmin
    app_image: "{{image}}"
    task_definition_name: morfeus-admin
    app_memory_soft_limit: 128
    memory_hard_limit: 4096
    container_port: 80
    host_port: 0
    task_cpu: 128
    #task_memory: 1024
    host_name: webserver
    host: http://18.220.64.40:80
    volume_name: nginx-volume
    source_path: /var/log/nginx-volume
    container_path: /nginx-volume

  


  morfeus-app:
    app_name: morfeus-app-3-3-1
    app_image: 769585693008.dkr.ecr.us-east-2.amazonaws.com/backend:latest
    task_definition_name: morfeus
    container_port: 80
    #memory_hard_limit: 4096
    host_port: 0
    task_cpu: 128
    task_memory: 1024
    host_name: webserver
    host: http://18.220.64.40:80
    volume_name1: nginx-volume
    source_path1: /var/log/nginx-volume
    container_path1: /nginx-volume
    volume_name2: nginx-volumes
    source_path2: /var/log/nginx-volumes
    container_path2: /nginx-volumes








