applications:
 
  triniti-3-3-1:
    app_name: triniti-3-3-1
    app_image: "{{image}}"
    task_definition_name: ai-runtime-server
    memory_hard_limit: 10240
    container_port: 80
    host_port: 80
    host_name: TRINITI_SPOTTER_END_POINT
    host: http://172.16.5.190:9000/v/1/spotter/process
    volume_name: superviser
    source_path: /var/log/supervisor
    container_path: /var/log/supervisor
    
    
  sniper-worker:
    app_name: spiner-worker
    app_image: "{{image}}"
    task_definition_name: sniper-worker
    memory_hard_limit: 10240
    container_port: 8888
    host_port: 9000
    host_name: webserver
    host: http://18.220.64.40:80
    volume_name1: spiner
    source_path1: /sniper
    container_path1: /opt/tornado/data/faq_index
    volume_name2: spiner-logs
    source_path2: /var/log/supervisor
    container_path2: /var/log/supervisor
   
 
  
  

   
   
  
  








