applications:
  morfeusadmin:
    app_name: active-ai
    app_image: nginx:latest
    container_port: 80
    host_port: 0
    task_cpu: 128
    task_memory: 1024
    host_name: webserver
    host: http://18.220.64.40:80
    volume_name1: nginx-volume
    source_path1: /var/log/nginx-volume
    container_path1: /nginx-volume
    volume_name2: superviser1
    source_path2: /var/log/superviser
    container_path2: /superviser

  
  

  morfeus-preprod:
    app_name: doublevolume
    app_image: 769585693008.dkr.ecr.us-east-2.amazonaws.com/backend:latest
    container_port: 80
    host_port: 0
    task_cpu: 128
    task_memory: 1024
    host_name: webserver
    host: http://18.220.64.40:80
    volume_name1: nginx-volume
    source_path1: /var/log/nginx-volume
    container_path1: /nginx-volume
    volume_name2: superviser
    source_path2: /var/log/superviser
    container_path2: /superviser


 
  
  

   
   
  
  








