applications:
  
  morfeusadmin:
    app_name: active-ai
    app_image: nginx:latest
    container_port: 80
    host_port: 0
    task_cpu: 128
    task_memory: 1024
    host_name: webserver
    host: http://18.220.64.40:80
    volume_name: nginx-volume
    source_path: /var/log/nginx-volume
    container_path: /nginx-volume
 
 

 
  
  

   
   
  
  








