#VPC Details
vpc_id: "vpc-95ed50fe"
cluster_name: Active-AI-Test

#Container details
alb_listener_port: 80
tg_port: 80
tg_unhealthy_threshold_count: 2
tg_healthy_threshold_count: 2
tg_health_check_timeout: 120
tg_health_check_interval: 300
tg_health_check_path: /
tg_successful_response_codes: 200

security_group_id: sg-002d0a85d94299b69
subnet_id_1: subnet-7ec6d504
subnet_id_2: subnet-a2a005c9


minimum_healthy_percent: 100
maximum_percent: 200
